development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: weixin_development 
  pool: 5
  username: weixin
  password: 6yhnmju7
  host: 115.29.36.94
  port: 3306


production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: weixin_release
  pool: 5
  username: weixin
  password: 6yhnmju7
  host: 115.29.36.94 
  port: 3306
