development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: weixin_development
  pool: 5
  username: root
  password: ''
  host: 127.0.0.1
  port: 3306


production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: weixin_release
  pool: 5
  username: vidaprint
  password: vida_huxia001@
  host: 42.121.111.102
  port: 3306
